// Seed data — loaded once if localStorage is empty
const PRO_SEED = [
  {id:1,name:'RASHID ROCHA ALI',pp:'AK0887406',phone:'',position:'STEEL FIXER',company:'NAYA ISHA',country:'',stage:'PENDING OFFER LETTER',submitted:46085,interview:'CV SELECTION',ol:'',mol:'',visa:'',travel:'',commission:'',paid:''},
  {id:2,name:'EDWIN KIPCHUBA LIMO',pp:'BK1190770',phone:'',position:'CONSTRUCTION HELPER',company:'NAYA ISHA',country:'',stage:'PENDING OFFER LETTER',submitted:46085,interview:'CV SELECTION',ol:'',mol:'',visa:'',travel:'',commission:'',paid:''},
  {id:3,name:'FELIX OGINGA OGANGO',pp:'BK460095',phone:'',position:'STEEL FIXER',company:'NAYA ISHA',country:'',stage:'PENDING OFFER LETTER',submitted:46085,interview:'CV SELECTION',ol:'',mol:'',visa:'',travel:'',commission:'',paid:''},
  {id:4,name:'JOHN KAGECHU GACHUHI',pp:'BK1148578',phone:'',position:'MASON',company:'NAYA ISHA',country:'',stage:'PENDING OFFER LETTER',submitted:46085,interview:'CV SELECTION',ol:'',mol:'',visa:'',travel:'',commission:'',paid:''},
  {id:5,name:'ERICK WAMALWA',pp:'AK0306347',phone:'',position:'HYDRAULIC MECHANIC',company:'',country:'',stage:'PENDING OFFER LETTER',submitted:46148,interview:46153,ol:'',mol:'',visa:'',travel:'',commission:'',paid:''},
  {id:6,name:'CLEOPHAS ONSOTI NYANGAU',pp:'BK352350',phone:'',position:'TISSUE FACTORY HELPER',company:'ULTRA CARE',country:'',stage:'PENDING OFFER LETTER',submitted:46160,interview:46160,ol:'',mol:'',visa:'',travel:'',commission:'',paid:''},
  {id:7,name:'RODGERS BENE SIKWE',pp:'AK1209164',phone:'',position:'TISSUE FACTORY HELPER',company:'ULTRA CARE',country:'',stage:'PENDING OFFER LETTER',submitted:46158,interview:46160,ol:'',mol:'',visa:'',travel:'',commission:'',paid:''},
  {id:8,name:'SHAQUILLE OLIMA ONEAL',pp:'BK1176461',phone:'',position:'TISSUE FACTORY HELPER',company:'ULTRA CARE',country:'',stage:'PENDING OFFER LETTER',submitted:46158,interview:46160,ol:'',mol:'',visa:'',travel:'',commission:'',paid:''},
  {id:9,name:'JOSEPH KEYARI MABONGA',pp:'AK0509587',phone:'',position:'TISSUE FACTORY HELPER',company:'ULTRA CARE',country:'',stage:'PENDING OFFER LETTER',submitted:46070,interview:'INTERVIEW',ol:'',mol:'',visa:'',travel:'',commission:'',paid:''},
  {id:10,name:'COLLINS MUTHOMI MICHENI',pp:'BK499597',phone:'',position:'FLAGMAN',company:'EB',country:'',stage:'PENDING MOL',submitted:46069,interview:46045,ol:46050,mol:'',visa:'',travel:'',commission:'',paid:''},
  {id:11,name:'DOUGLAS KAMAU KIRUBI',pp:'AK0388727',phone:'',position:'CLEANER',company:'HPBS',country:'',stage:'PENDING MOL',submitted:46064,interview:'CV SELECTION',ol:46074,mol:'',visa:'',travel:'',commission:'',paid:''},
  {id:12,name:'ZETH WANYONYI',pp:'BK1129720',phone:'',position:'CLEANER',company:'HPBS',country:'',stage:'PENDING MOL',submitted:46064,interview:'CV SELECTION',ol:46074,mol:'',visa:'',travel:'',commission:'',paid:''},
  {id:13,name:'BENSON WANJOHI WAINAINA',pp:'BK310553',phone:'',position:'CHEF',company:'MMARI',country:'',stage:'PENDING MOL',submitted:46125,interview:46146,ol:46160,mol:'',visa:'',travel:'',commission:'',paid:''},
  {id:14,name:'DENNIS NGANGA KIARIE',pp:'BK1117831',phone:'',position:'CLEANER',company:'EB',country:'',stage:'PENDING VISA',submitted:46062,interview:'CV SELECTION',ol:46064,mol:46080,visa:'',travel:'',commission:'',paid:''},
  {id:15,name:'STANLEY KISOVI KITENGE',pp:'BK987506',phone:'',position:'SECURITY GUARD',company:'HPBS',country:'',stage:'PENDING VISA',submitted:46064,interview:46066,ol:46074,mol:46163,visa:'',travel:'',commission:'',paid:''},
  {id:16,name:'ZAKAYO KAGUNDA MWANGI',pp:'AK1488443',phone:'',position:'SECURITY GUARD',company:'HPBS',country:'',stage:'PENDING VISA',submitted:46064,interview:46066,ol:46074,mol:46163,visa:'',travel:'',commission:'',paid:''},
  {id:17,name:'CHARLES OMOSA NYAKUNDI',pp:'CK151396',phone:'',position:'FLAGMAN',company:'EB',country:'',stage:'PENDING VISA',submitted:46069,interview:46045,ol:46050,mol:46163,visa:'',travel:'',commission:'',paid:''},
  {id:18,name:'NELLY MURINGA KIMANI',pp:'AK1293328',phone:'',position:'HOTEL HOUSEKEEPER',company:'SUNDAY',country:'',stage:'PENDING TRAVEL',submitted:45999,interview:45999,ol:46006,mol:46049,visa:46077,travel:'',commission:150000,paid:140000},
  {id:19,name:'LENSON NJUGUNA NYAMBURA',pp:'BK478106',phone:'',position:'SECURITY GUARD',company:'HPBS',country:'',stage:'PENDING TRAVEL',submitted:46064,interview:46066,ol:46074,mol:46151,visa:46164,travel:'',commission:'',paid:''},
  {id:20,name:'PATRICK MUGO GITAKA',pp:'AK1457247',phone:'',position:'SECURITY GUARD',company:'POWER SOL',country:'',stage:'TRAVELLED',submitted:45933,interview:45938,ol:45985,mol:45997,visa:46002,travel:46013,commission:'',paid:''},
  {id:21,name:'KELVIN MUTUMA LAWRENCE',pp:'BK1204704',phone:'',position:'TISSUE FACTORY HELPER',company:'ULTRA CARE',country:'',stage:'TRAVELLED',submitted:46000,interview:46000,ol:46001,mol:46022,visa:46036,travel:46048,commission:'',paid:''},
  {id:22,name:'SAMUEL NJAAGA NJUGUNA',pp:'BK535743',phone:'',position:'TISSUE FACTORY HELPER',company:'ULTRA CARE',country:'',stage:'TRAVELLED',submitted:46000,interview:46000,ol:46002,mol:46011,visa:46036,travel:46048,commission:'',paid:''},
  {id:23,name:'LIVINGSTONE MWANZI MWAMBURI',pp:'BK149513',phone:'',position:'FLAGMAN',company:'EB',country:'',stage:'TRAVELLED',submitted:46006,interview:46007,ol:46013,mol:46024,visa:46052,travel:46063,commission:'',paid:''},
  {id:24,name:'CYNTHIA KIRIGO MUTAHI',pp:'BK378890',phone:'',position:'HOTEL HOUSEKEEPER',company:'SUNDAY',country:'',stage:'TRAVELLED',submitted:45967,interview:45999,ol:46006,mol:46049,visa:46071,travel:46097,commission:150000,paid:140000},
  {id:25,name:'NELLY MACHARIA',pp:'AK1613170',phone:'',position:'HOTEL HOUSEKEEPER',company:'SUNDAY',country:'',stage:'TRAVELLED',submitted:45986,interview:45999,ol:46006,mol:46049,visa:46073,travel:46097,commission:160000,paid:150000},
  {id:26,name:'WAYNE JUMA HAMISI',pp:'BK1241317',phone:'',position:'FLAGMAN',company:'EB',country:'',stage:'TRAVELLED',submitted:46044,interview:46045,ol:46050,mol:46059,visa:46070,travel:46120,commission:'',paid:''},
  {id:27,name:'VINCENT JEREMIAH WATANI',pp:'BK1140833',phone:'',position:'FLAGMAN',company:'EB',country:'',stage:'TRAVELLED',submitted:46006,interview:46011,ol:46017,mol:46059,visa:46071,travel:46120,commission:130000,paid:110000},
  {id:28,name:'MARTIN NJOROGE PERE',pp:'BK038256',phone:'',position:'FLAGMAN',company:'EB',country:'',stage:'TRAVELLED',submitted:46006,interview:46008,ol:46013,mol:46059,visa:46070,travel:46120,commission:'',paid:''},
  {id:29,name:'FELIX MBOGO MUGENDI',pp:'BK1111459',phone:'',position:'SECURITY GUARD',company:'EB',country:'',stage:'TRAVELLED',submitted:46027,interview:46028,ol:46034,mol:46065,visa:46071,travel:46120,commission:'',paid:''},
  {id:30,name:'ENOCK RUBIA LIGARI',pp:'BK801171',phone:'',position:'TISSUE FACTORY HELPER',company:'ULTRA CARE',country:'',stage:'TRAVELLED',submitted:46070,interview:46071,ol:46077,mol:46107,visa:46113,travel:46131,commission:130000,paid:120000},
  {id:31,name:'DENNIS THIONGO KAMAU',pp:'BK661958',phone:'',position:'TISSUE FACTORY HELPER',company:'ULTRA CARE',country:'',stage:'TRAVELLED',submitted:46070,interview:46071,ol:46077,mol:46112,visa:46118,travel:46131,commission:130000,paid:117000},
  {id:32,name:'STEAVEN OCHIENG OJWANG',pp:'BK1188220',phone:'',position:'CLEANER',company:'HPBS',country:'',stage:'TRAVELLED',submitted:46064,interview:'CV SELECTION',ol:46074,mol:46122,visa:46127,travel:46145,commission:'',paid:''},
  {id:33,name:'JOHN MUTINDA MUE',pp:'BK1053669',phone:'',position:'FLAGMAN',company:'EB',country:'',stage:'TRAVELLED',submitted:46069,interview:46045,ol:46050,mol:46065,visa:46094,travel:46145,commission:130000,paid:120000},
  {id:34,name:'BARTICAN BOTHIC EMBA',pp:'BK315057',phone:'',position:'FLAGMAN',company:'EB',country:'',stage:'TRAVELLED',submitted:46069,interview:46045,ol:46050,mol:46080,visa:46094,travel:46145,commission:'',paid:''},
  {id:35,name:'JACOB OMWA OBADHA',pp:'BK246472',phone:'',position:'PLANT HELPER',company:'EB',country:'',stage:'TRAVELLED',submitted:46062,interview:'CV SELECTION',ol:46064,mol:46080,visa:46094,travel:46145,commission:'',paid:''},
  {id:36,name:'JOSEPH MUTHEE MUGO',pp:'AK0100651',phone:'',position:'CLEANER',company:'EB',country:'',stage:'TRAVELLED',submitted:46062,interview:'CV SELECTION',ol:46064,mol:46080,visa:46094,travel:46145,commission:'',paid:''},
  {id:37,name:'NICHOLAS MASAWE NJENGA',pp:'BK987503',phone:'',position:'SECURITY GUARD',company:'HPBS',country:'',stage:'TRAVELLED',submitted:46064,interview:46066,ol:46074,mol:46092,visa:46106,travel:46157,commission:'',paid:''}
];

const LB_SEED = [
  {id:1,name:'MONICA WANGECI MWANGI',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:150,r1Date:'',r1Amt:75,r2Date:'',r2Amt:75,notes:''},
  {id:2,name:'DAISY CHEPNGENO MUTAI',phone:'',ppStatus:'HAD PP',travelStatus:'TRAVELLED',travelDate:'',toRefund:0,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:3,name:'SHARON ADHIAMBO',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:4,name:'BERYL AKINYI OKOTH',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:5,name:'MARY ANN NJERI NYAMBURA',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:6,name:'WINFRED WACUKA',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:0,notes:''},
  {id:7,name:'NANCY NJOKI',phone:'',ppStatus:'PUSHED',travelStatus:'TRAVELLED',travelDate:'',toRefund:100,r1Date:'',r1Amt:100,r2Date:'',r2Amt:0,notes:''},
  {id:8,name:'PENINNAH MAYAKA',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:9,name:'MILLICENT WANGA',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:10,name:'FELISTER RONO',phone:'',ppStatus:'HAD PP',travelStatus:'TRAVELLED',travelDate:'',toRefund:0,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:11,name:'LUCY GACHANGA',phone:'',ppStatus:'APPLIED',travelStatus:'NOT TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:12,name:'EMMACULATE JONYO',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:13,name:'EUNICE AWUOR',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:0,notes:'RETURNED'},
  {id:14,name:'AGNES WANGA',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:15,name:'ROSE MAYAKA',phone:'',ppStatus:'HAD PP',travelStatus:'TRAVELLED',travelDate:'',toRefund:0,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:16,name:'TEKRA JOAN',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:17,name:'MAGDALINE NJERI KAMAU',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:18,name:'STACY MORAA',phone:'',ppStatus:'HAD PP',travelStatus:'TRAVELLED',travelDate:'',toRefund:0,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:19,name:'RACHAEL WANJIRU NGERO',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:0,notes:'to clear balance this month'},
  {id:20,name:'JOYCE WANJIKU MAINA',phone:'',ppStatus:'PUSHED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:0,notes:''},
  {id:21,name:'IRENE AKWISO',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:22,name:'GLADYS NYABOKE NYAKUNDI',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:23,name:'HANNAH NJERI GIKONYO',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:'RETURNED'},
  {id:24,name:'NAOMI WANJIRU MBURU',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:25,name:'ABIGAEL SHIREKU NDETE',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:26,name:'DIANA NANJALA WANYONYI',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:27,name:'DAMARIS MORAA NYABUTO',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:28,name:'BRENDA KEMUMA MUTANDA',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:0,notes:'RETURNED'},
  {id:29,name:'REGINA MUTHONI CHEGE',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:30,name:'VIVIAN NJERI KAIRU',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:31,name:'FRIDA NGITHI NJAGI',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:32,name:'EMMA MORAA NYAMWEYA',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:33,name:'NOEL NEKESA SIMIYU',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:34,name:'FAITH RACHAEL MUNYONYO',phone:'',ppStatus:'HAD PP',travelStatus:'TRAVELLED',travelDate:'',toRefund:0,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:35,name:'PURITY BOSIBORI',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:36,name:'EUNICE BARONGO MBAKA',phone:'',ppStatus:'APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:200,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:37,name:'CHARITY WANJIRU NGARI',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:38,name:'RUTH WAMBUI MBUGUA',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:39,name:'JANE NJERI MBURU',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:40,name:'ESTHER MUMBI NJERI',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:41,name:'SYLVIA WAMAITHA WANJIRU',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:42,name:'CHRISTINE ANYANGO ANDHERE',phone:'',ppStatus:'APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:200,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:43,name:'MARY WANJIRU WAIRIMU',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:44,name:'MARY NJERI',phone:'',ppStatus:'HAD PP',travelStatus:'NOT YET',travelDate:'',toRefund:0,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:45,name:'ROSELINE WAWIRA',phone:'',ppStatus:'HAD PP',travelStatus:'TRAVELLED',travelDate:'',toRefund:0,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:46,name:'SHEILA JEPKORIR',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:47,name:'DIANAH KEMUNTO NYANDUSI',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:48,name:'DORCA NYABATE NYANDUSI',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:49,name:'ELIZABETH NJERI NDUNGU',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:0,notes:'to clear balance this month'},
  {id:50,name:'SUSAN REHEMA MAKUTWA',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:51,name:'ISABELLA BOSIBORI NYAMOTE',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:52,name:'RUTH MBUGUA',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:53,name:'LEAH WANGARI KARARI',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:0,notes:'completely offline'},
  {id:54,name:'REBECCA SIFA SIMIYU',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:'RETURNED'},
  {id:55,name:'LOVIANCE ATIENO',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:56,name:'BETH WANGARE',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:57,name:'JANET KWAMBOKA NYANDUSI',phone:'',ppStatus:'APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:200,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:58,name:'SUSAN NYOKABI MUTHUI',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:59,name:'NANCY NYAWIRA MAINA',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:60,name:'JOYCE WAMBUI KAHURA',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:61,name:'RUTH BOSIBORI NYANDUSI',phone:'',ppStatus:'APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:200,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:62,name:'FAITH KANGAI',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:63,name:'VENAH MORAA NYAKUNDI',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:64,name:'ESTHER KWAMBOKA MOGAKA',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:65,name:'TERESIAH WANJIKU ANAMWENE',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:66,name:'BRENDA NJOKI NJERU',phone:'',ppStatus:'APPLIED',travelStatus:'NOT TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:67,name:'EZNA MORAA',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:68,name:'DIVINA MORAA ONYANCHA',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:69,name:'HANNAH WAITHERA NJOKI',phone:'',ppStatus:'HAD PP',travelStatus:'TRAVELLED',travelDate:'',toRefund:0,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:70,name:'MAUREEN WAMBUI WANJIKU',phone:'',ppStatus:'APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:200,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:71,name:'ELIZABETH WANJIKU',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:72,name:'MERCY MORAA KOMBESA',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:73,name:'JACKLINE NYABIAGE NYARORI',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:74,name:'ROSE ADISA',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:75,name:'PHYLIS MUONJA',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:76,name:'MERCY NYAMBURA MARIARA',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:0,notes:'said she has cleared, waiting for receipt'},
  {id:77,name:'CYNTHIA KWAMBOKA GUTO',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:78,name:'DIVINAH KWAMBOKA NYANDIKO',phone:'',ppStatus:'APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:200,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:79,name:'MAUREEN BOYANI OBIRI',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:80,name:'DELPHINE MANOTI MEROKA',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:100,r2Date:'',r2Amt:100,notes:''},
  {id:81,name:'MILKA WANGARI MUNYI',phone:'',ppStatus:'APPLIED',travelStatus:'TRAVELLED',travelDate:'',toRefund:200,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:'not responding'},
  {id:82,name:'JACKLINE MWELU MUTUKU',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:83,name:'MARY WAGIO NJENGA',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:84,name:'GLADYS NYATICHI GILBERT',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:85,name:'OMBOGO NYABONYI RISPER',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:86,name:'EUNICE WANGECI KARIUKI',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:87,name:'IRENE NJERI WAMBUI',phone:'',ppStatus:'HAD PP',travelStatus:'TRAVELLED',travelDate:'',toRefund:0,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:88,name:'EUNICE KWAMBOKA',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:89,name:'MAUREEN KWAMBOKA',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:90,name:'ROSELYNE KWAMBOKA',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:91,name:'ROBINA BOCHERE',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:92,name:'FELMAH MORAA',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:93,name:'ROSEMARY MONCHARI',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:94,name:'PURITY NASIMIYU',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:95,name:'SARAH MONYANGI',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:96,name:'LUCY WANJIKU',phone:'',ppStatus:'NOT APPLIED',travelStatus:'NOT YET',travelDate:'',toRefund:250,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:97,name:'MARY NJAMBI KARIUKI',phone:'',ppStatus:'HAD PP',travelStatus:'TRAVELLED',travelDate:'',toRefund:0,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''},
  {id:98,name:'DORINE ABONGO OMONDI',phone:'',ppStatus:'HAD PP',travelStatus:'TRAVELLED',travelDate:'',toRefund:0,r1Date:'',r1Amt:0,r2Date:'',r2Amt:0,notes:''}
];
